models:
  - name: dim_employer
    description: "Infromation about the employer such as name, workplce address, organisation number e.tc."
    columns:
      - name: employer_id
        description: "Primary key, a surrgoate key based on columns: id, employer_name. "
        data_tests:
          - unique
          - not_null

      - name: workplace_city
        data_tests:
          - not_null

  - name: dim_job_details
    columns:
      - name: job_details_id
        description: "Details about the job ad"
        data_tests:
          - not_null
          - unique
      - name: headline
        data_tests:
          - not_null

  - name: fct_job_ads
    description: "The facts are relevance and vacancies"
    columns:
      - name: job_details_key
        data_tests:
          - relationships:
              to: ref('dim_job_details')
              field: job_details_id

  - name: mart_job_listings
    description: "Retrieve a detailed list of job ads with associated job details and employer information."
    columns:
      - name: driving_license
        data_tests:
          - not_null
            
          