api_secret_key = "api_secret_key" # please set me up!

[destination.snowflake.credentials]
database = "team_vard" # please set me up!
password = "Snowflake1337!" # please set me up!
username = "attaponsayod2" # please set me up!
host = "ij74709.west-europe.azure" # please set me up!
warehouse = "warehouse" # please set me up!
role = "role" # please set me up!
