api_secret_key = "api_secret_key" # please set me up!

[destination.snowflake.credentials]
database = "job_ads" # please set me up!
password = "extract_loader_password123" # please set me up!
username = "extract_loader" # please set me up!
host = "xi57324.west-europe.azure" # please set me up!
warehouse = "dev_wh" # please set me up!
role = "job_ads_dlt_role" # please set me up!
